document.contact.name.onkeypress=function(){
    document.getElementById('namealert').innerHTML="";
}
document.contact.email.onkeypress=function(){
    document.getElementById('emailalert').innerHTML="";
}
document.contact.company.onkeypress=function(){
    document.getElementById('companyalert').innerHTML="";
}
document.contact.timeframe.onkeypress=function(){
    document.getElementById('timeframealert').innerHTML="";
}
document.contact.details.onkeypress=function(){
    document.getElementById('detailsalert').innerHTML="";
}